
import type { Metadata } from "next";
import { ViewTransitions } from 'next-view-transitions'
import {  Noto_Naskh_Arabic, Noto_Sans, Archivo } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./components/Header";
import Footer from "./components/Footer";


const notoNaskhArabic = Noto_Naskh_Arabic({
  variable: "--font-noto-naskh-arabic",
  subsets: ["arabic"],
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "WikiCommons Wallpaper API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <ViewTransitions >
          <body
            className={`${archivo.variable} ${notoNaskhArabic.variable} ${notoSans.variable} antialiased`}
          >
            <Providers>
              <Header />
              {children}
              <Footer />
            </Providers>
          </body>
      </ViewTransitions>
    </html>
  );
}
